name: LaTeX

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX compilation
        uses: dante-ev/latex-action@latest
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: build_result
          path: |
            main.pdf
